name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Déclenche sur push vers main
  workflow_dispatch:  # Permet de déclencher manuellement

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages  # Pas de build pour site statique, mais prépare pour déploiement
      uses: actions/configure-pages@v5

    - name: Upload artifact  # Upload les fichiers statiques
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'  # Déploie depuis la racine (tout le dépôt)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4