name: Update JSON

permissions:
  contents: write  # Pour checkout, commit, push de data.json
  actions: write   # Pour déclencher d'autres actions si besoin

on:
  workflow_dispatch:
    inputs:
      new_data:
        description: 'Nouvelles parties JSON (tableau)'
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # Utilise votre fine-grained token

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update data.json
        run: |
          new_data='${{ github.event.inputs.new_data }}'
          # Si data.json n'existe pas, créez-le
          if [ ! -f data.json ]; then echo '[]' > data.json; fi
          jq --argjson new "$new_data" '. += $new' data.json > temp.json
          mv temp.json data.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m 'Update scores via Cloudflare Worker' || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
